"""empty message

Revision ID: 14268c91a40
Revises: 2659f342179
Create Date: 2014-09-28 03:08:42.632283

"""

# revision identifiers, used by Alembic.
revision = '14268c91a40'
down_revision = '2659f342179'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
