"""annotate store test

Revision ID: 161558bf33c
Revises: 490d64fe4d8
Create Date: 2014-10-25 11:30:11.846545

"""

# revision identifiers, used by Alembic.
revision = '161558bf33c'
down_revision = '490d64fe4d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
