""" 

Revision ID: 19582cec818
Revises: a6da46100d
Create Date: 2014-10-13 08:51:13.010752

"""

# revision identifiers, used by Alembic.
revision = '19582cec818'
down_revision = 'a6da46100d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
