"""linkedin

Revision ID: 1b74a29f31a
Revises: 3e5620f4cee
Create Date: 2014-10-10 20:43:00.354905

"""

# revision identifiers, used by Alembic.
revision = '1b74a29f31a'
down_revision = '3e5620f4cee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
