"""annotations on staging

Revision ID: 1ef02d5190a
Revises: 4c3f492882c
Create Date: 2014-10-25 22:29:22.332546

"""

# revision identifiers, used by Alembic.
revision = '1ef02d5190a'
down_revision = '4c3f492882c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
