"""tags

Revision ID: 1f416f33985
Revises: 5009d76ce92
Create Date: 2014-09-23 23:38:07.308860

"""

# revision identifiers, used by Alembic.
revision = '1f416f33985'
down_revision = '5009d76ce92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
