"""comment system

Revision ID: 2659f342179
Revises: 29df7b7c14f
Create Date: 2014-09-24 15:14:56.018970

"""

# revision identifiers, used by Alembic.
revision = '2659f342179'
down_revision = '29df7b7c14f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
