"""empty message

Revision ID: 295437fb472
Revises: 473b4ad11fc
Create Date: 2014-10-09 13:56:50.272919

"""

# revision identifiers, used by Alembic.
revision = '295437fb472'
down_revision = '473b4ad11fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
