"""text

Revision ID: 29df7b7c14f
Revises: 2d5734c92bc
Create Date: 2014-09-24 11:48:49.259465

"""

# revision identifiers, used by Alembic.
revision = '29df7b7c14f'
down_revision = '2d5734c92bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_name', table_name='tags')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tags_name', 'tags', ['name'], unique=1)
    ### end Alembic commands ###
