"""update

Revision ID: 2a6f7a856af
Revises: 3b7286c6ad8
Create Date: 2014-10-14 19:43:05.125870

"""

# revision identifiers, used by Alembic.
revision = '2a6f7a856af'
down_revision = '3b7286c6ad8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
