"""mailchimp

Revision ID: 2ca103ca2bc
Revises: 4aea875fa56
Create Date: 2014-10-22 00:37:48.594396

"""

# revision identifiers, used by Alembic.
revision = '2ca103ca2bc'
down_revision = '4aea875fa56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
