"""empty message

Revision ID: 2d5734c92bc
Revises: 1f416f33985
Create Date: 2014-09-24 08:16:29.743899

"""

# revision identifiers, used by Alembic.
revision = '2d5734c92bc'
down_revision = '1f416f33985'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
