"""major redesign

Revision ID: 2e444752899
Revises: 2ca103ca2bc
Create Date: 2014-10-24 00:53:53.056627

"""

# revision identifiers, used by Alembic.
revision = '2e444752899'
down_revision = '2ca103ca2bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
