"""annotate store test

Revision ID: 3aaf42c902a
Revises: 49c5d4ab476
Create Date: 2014-10-25 11:41:30.300131

"""

# revision identifiers, used by Alembic.
revision = '3aaf42c902a'
down_revision = '49c5d4ab476'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
