"""final draft

Revision ID: 3b9f15410f
Revises: 47e374cc84d
Create Date: 2014-09-29 04:05:43.814821

"""

# revision identifiers, used by Alembic.
revision = '3b9f15410f'
down_revision = '47e374cc84d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
