"""json structure update

Revision ID: 3e5620f4cee
Revises: 58b09bc3524
Create Date: 2014-10-09 17:05:49.047946

"""

# revision identifiers, used by Alembic.
revision = '3e5620f4cee'
down_revision = '58b09bc3524'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
