"""annotate store test

Revision ID: 44799eb49ca
Revises: 3aaf42c902a
Create Date: 2014-10-25 11:54:43.810701

"""

# revision identifiers, used by Alembic.
revision = '44799eb49ca'
down_revision = '3aaf42c902a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
