"""annotate store test

Revision ID: 4692e557927
Revises: 2e444752899
Create Date: 2014-10-25 09:59:39.788602

"""

# revision identifiers, used by Alembic.
revision = '4692e557927'
down_revision = '2e444752899'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('uri', sa.String(length=120), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.String(length=120), nullable=True),
    sa.Column('end', sa.String(length=120), nullable=True),
    sa.Column('startOffset', sa.Integer(), nullable=True),
    sa.Column('endOffset', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_created'), 'annotations', ['created'], unique=False)
    op.create_index(op.f('ix_annotations_updated'), 'annotations', ['updated'], unique=False)
    op.create_index(op.f('ix_annotations_uri'), 'annotations', ['uri'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotations_uri'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_updated'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_created'), table_name='annotations')
    op.drop_table('annotations')
    ### end Alembic commands ###
