"""empty message

Revision ID: 473b4ad11fc
Revises: 3b9f15410f
Create Date: 2014-10-09 08:06:14.359306

"""

# revision identifiers, used by Alembic.
revision = '473b4ad11fc'
down_revision = '3b9f15410f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
