"""final draft

Revision ID: 47e374cc84d
Revises: 4b21bdcc89c
Create Date: 2014-09-29 03:27:22.808721

"""

# revision identifiers, used by Alembic.
revision = '47e374cc84d'
down_revision = '4b21bdcc89c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
