"""annotate store test

Revision ID: 490d64fe4d8
Revises: 59d24810b41
Create Date: 2014-10-25 11:26:37.320747

"""

# revision identifiers, used by Alembic.
revision = '490d64fe4d8'
down_revision = '59d24810b41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_annotations_uri', table_name='annotations')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_annotations_uri', 'annotations', ['uri'], unique=1)
    ### end Alembic commands ###
