"""annotate store test

Revision ID: 49c5d4ab476
Revises: 161558bf33c
Create Date: 2014-10-25 11:31:41.174635

"""

# revision identifiers, used by Alembic.
revision = '49c5d4ab476'
down_revision = '161558bf33c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
