"""keen and newrelic

Revision ID: 4aea875fa56
Revises: 2a6f7a856af
Create Date: 2014-10-16 08:13:17.431791

"""

# revision identifiers, used by Alembic.
revision = '4aea875fa56'
down_revision = '2a6f7a856af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
