"""final draft

Revision ID: 4b21bdcc89c
Revises: 14268c91a40
Create Date: 2014-09-28 20:06:36.642834

"""

# revision identifiers, used by Alembic.
revision = '4b21bdcc89c'
down_revision = '14268c91a40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
