"""fixes

Revision ID: 4c0fcbe4629
Revises: 2ca28381576
Create Date: 2014-10-13 21:09:05.419643

"""

# revision identifiers, used by Alembic.
revision = '4c0fcbe4629'
down_revision = '2ca28381576'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
