"""annotations on staging

Revision ID: 4c3f492882c
Revises: 51761f394dc
Create Date: 2014-10-25 14:48:56.613816

"""

# revision identifiers, used by Alembic.
revision = '4c3f492882c'
down_revision = '51761f394dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
