"""tags

Revision ID: 5009d76ce92
Revises: 788454eac8
Create Date: 2014-09-23 21:55:13.670041

"""

# revision identifiers, used by Alembic.
revision = '5009d76ce92'
down_revision = '788454eac8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
