"""annotate store test

Revision ID: 51761f394dc
Revises: 44799eb49ca
Create Date: 2014-10-25 12:02:50.747845

"""

# revision identifiers, used by Alembic.
revision = '51761f394dc'
down_revision = '44799eb49ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
