"""empty message

Revision ID: 58b09bc3524
Revises: 295437fb472
Create Date: 2014-10-09 14:58:13.570022

"""

# revision identifiers, used by Alembic.
revision = '58b09bc3524'
down_revision = '295437fb472'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
