"""annotate store test

Revision ID: 59d24810b41
Revises: 4692e557927
Create Date: 2014-10-25 10:15:33.783307

"""

# revision identifiers, used by Alembic.
revision = '59d24810b41'
down_revision = '4692e557927'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
