"""big update

Revision ID: 5ac1de91ab9
Revises: 9cf2481502
Create Date: 2014-10-13 20:19:14.181289

"""

# revision identifiers, used by Alembic.
revision = '5ac1de91ab9'
down_revision = '9cf2481502'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
