"""comment system

Revision ID: 788454eac8
Revises: 4ff13e88149
Create Date: 2014-09-23 21:10:00.078772

"""

# revision identifiers, used by Alembic.
revision = '788454eac8'
down_revision = '4ff13e88149'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entries_url'), 'entries', ['url'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_url'), table_name='entries')
    ### end Alembic commands ###
