""".env fix

Revision ID: 9cf2481502
Revises: 19582cec818
Create Date: 2014-10-13 11:26:32.155191

"""

# revision identifiers, used by Alembic.
revision = '9cf2481502'
down_revision = '19582cec818'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
