"""fix oauth

Revision ID: a6da46100d
Revises: 1b74a29f31a
Create Date: 2014-10-13 06:12:38.100637

"""

# revision identifiers, used by Alembic.
revision = 'a6da46100d'
down_revision = '1b74a29f31a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
